export default {
  USERS_RECEIVED: 'USERS_RECEIVED',
  USER_CREATED: 'USER_CREATED',
  USER_LOGGED_IN: 'USER_LOGGED_IN',
  CURRENT_USER_RECEIVED: 'CURRENT_USER_RECEIVED',
  USER_LOGGED_OUT: 'USER_LOGGED_OUT',

  POST_CREATED: 'POST_CREATED',
  FETCH_POSTS: 'FETCH_POSTS',
  FETCH_POST: 'FETCH_POST'
};
